package card;

public enum CaseEffects {
    
    BOARD_BUFF,//0
    SINGLE_TEMP_BUFF,//1
    CREATE_CARD,//2 LEMBRAR DE RESOLVER INSTANCIAS DIFERENTES CAUSADAS POR CARTAS QUE CRIAM CARTAS NOVAS NA MAO
    FULL_HEAL,//3
    DOUBLE_STATS,//4
    SINGLE_COMBAT,//5
    ALLY_STRIKE_NEXUS,//6
    JUDGEMENT,//7
    DRAW_CARD,//8
    ZERO_POWER,//9
    PRISMATIC_BARRIER,//10
    DAMAGE_NEXUS,//11
    REMOVE_TEMP_BUFF,//12
    EVOLUTION,//13
    STRONGEST_ZERO_POWER,//14
    FULL_AOE,//15
    SELF_BUFF,//16
    AREA_TEMP_BUFF,//17
    REMOVE_BARRIER,//18
    DAMAGE_ANYTHING,//19
    OPPONENT_AOE,//20
    ANIVIA_TRANSFORMATION,//21
    SHATTER,//22
    CATALYST//23

}
