package card;

public enum CaseEffects {
    //O DETALHAMENTO DE CADA EFEITO PODE SER VISTO NO MÉTODO APPLYEFFECTS DA CLASSE EFFECT
    
    BOARD_BUFF,
    SINGLE_TEMP_BUFF,
    CREATE_CARD,
    FULL_HEAL,
    DOUBLE_STATS,
    SINGLE_COMBAT,
    ALLY_STRIKE_NEXUS,
    JUDGEMENT,
    DRAW_CARD,
    ZERO_POWER,
    PRISMATIC_BARRIER,
    DAMAGE_NEXUS,
    REMOVE_TEMP_BUFF,
    EVOLUTION,
    STRONGEST_ZERO_POWER,
    FULL_AOE,
    SELF_BUFF,
    AREA_TEMP_BUFF,
    REMOVE_BARRIER,
    DAMAGE_ANYTHING,
    OPPONENT_AOE,
    ANIVIA_TRANSFORMATION,
    SHATTER,
    CATALYST

}
